### ISSUE TITLE
File Upload is not correct

### ISSUE THREAD

**Issue by Aetrax** [darryldecode/laravel-starter-kit#11]
Hi, this is my first time using GitHub in this way, im not sure if i do this correct but i think someone will correct me if needed. 

The File-Upload is not working, i think you are using the wrong function in your BaseRepository.

It only works if you change the "delete" to destroy on your delete function.

At the SPAController you need some redirect if the session expires. If the User wont refresh there would be no problem, but if he does he would get a error message because the "setUser" function has no User instance anymore. Ugly workaround would be "if $user == null  { redirect to login}".

**Comment by Aetrax** [comment]
If you take the raw project and try to delete a uploaded file, the file wont disappear. The Thumb will not be present, but thats all. If you change the delete function at the Baserepository to 

    /**
     * @param int $id
     * @return bool|null
     * @throws \Exception
     */
    public function delete(int $id)
    {  
        return $this->model->destroy($id);
    }

the File gets deleted. Could also be that i did something wrong as i worked me through your code ^^`.

I had to tweek the deleting of the stored filed too, didnt work at first.

Does your project work if you clone a new project?

And if you go to config/session.php and set the sessoin time to 1, and refresh the page after 1 minute you will get an error message.

**Comment by Aetrax** [comment]
A listener on the Events like "FILE DELETED" that refreshs the files would also be a good thing. 

So you loadFiles() after the trash function at the mounted hook. 

            self.$eventBus.$on('FILE_DELETED', function () {
                self.loadFiles(()=>{});
            });
            self.$eventBus.$on('FILE_UPLOADED', function () {
                self.loadFiles(()=>{});
            });

"Could also be combinated."

**Comment by darryldecode** [comment]
@Aetrax thank you for pointing out 👍  I wonder what had happen. I just pushed a fix. Thanks again!
