### ISSUE TITLE
419 Sorry, your session has expired. Please refresh and try again.

### ISSUE THREAD

**Issue by vokuev** [darryldecode/laravel-starter-kit#12]
419
Sorry, your session has expired. Please refresh and try again.

**Comment by darryldecode** [comment]
Hello, can you elaborate more of the scenario that you are getting this error?

**Comment by vokuev** [comment]
on the page: /login, after entering username and password

**Comment by vokuev** [comment]
m?

**Comment by Saadelk** [comment]
i have the same issue now too, same scenario as @vokuev , anyone can help ?

**Comment by hugohcn** [comment]
The same with me..

I spent a lot of hours trying to fix it! However, I can't find any reason for that!

I made 2 downgrades of Laravel framework and now I really don't know what to do!

It's happening only in production environment. :/
At localhost, it works fine! :(
