### ISSUE TITLE
How to display created_by on the user listing view

### ISSUE THREAD

**Issue by clawes** [darryldecode/laravel-starter-kit#14]
Great starter template!

I have  1 issue:

I would like the user listing to show the name of the user who created that user record under the column name "Created By".     It is not obvious to me how to update the listUsers function in UserRepository class to include addition columns or custom queries.

Thanks for suggestion.

**Comment by darryldecode** [comment]
Hi, the user list function is handled in UserController can be found in Http/Controllers/admin/UserController@listUsers() .. Created By is not built in on the starter kit. Please extend the app to fit your needs. Happy coding!
