### ISSUE TITLE
the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5.

### ISSUE THREAD

**Issue by blueamazon** [darryldecode/laravel-starter-kit#3]
warning  in ./resources/assets/js/components/UserLists.vue

(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.

i have tried changing "scope" to "slot-scope" bu still getting same errors.

**Comment by darryldecode** [comment]
ah let me check. Thanks for reporting 👍
