### ISSUE TITLE
Access to undeclared static property: App\Components\User\Models\UserMeta::$META_DATA

### ISSUE THREAD

**Issue by mwargan** [darryldecode/laravel-starter-kit#6]
Hi!

Looks like an error is being thrown using `with('getParseMeta')` and `User::find(1)->getParseMeta()`. 
`Access to undeclared static property: App\Components\User\Models\UserMeta::$META_DATA`

If I remove the foreach loop, I get another error:
`Call to undefined method stdClass::addEagerConstraints()`

`with('meta')` works as expected.

If I do `get()->getParseMeta()` I get Method getParseMeta does not exist.

Am I doing something wrong here?

**Comment by darryldecode** [comment]
Hello @mwargan thanks for reporting. This should be fixed now.  User::find(1)->getParseMeta() should be working now if being used. You cannot use "with('getParseMeta')" as this is not an accessor and no accessor is defined for this.
