### ISSUE TITLE
localisation support

### ISSUE THREAD

**Issue by BramEsposito** [darryldecode/laravel-starter-kit#7]
Thanks @darryldecode for a great starter kit. 

I wonder if you see the need for localization support? 

I'm happy to create a pull request with the changes I made in [my fork](https://github.com/BramEsposito/laravel-starter-kit)

**Comment by darryldecode** [comment]
Hi @BramEsposito , thank you for the interest on the project. I doubt if we would need it on the starter kit. I would prefer to only let the user decide whether they implement localization or not, and especially it's good if users are able to choose package they will use. Thanks again. I appreciate it.
